


SEARCHS_DIC = ["Restaurante", "Academia", "Sorveteria"] #ESTABELECIMENTOS QUE DESEJA CONSULTA
BASE_URL = "https://www.google.com/maps/search/" #BASE URL QUE SERA FEITA A CONSULTA

#CONFIGURACAO DO SELENIUM
HEADLESS = False # True: RODA EM SEGUNDO PLANO SEM MOSTRAR A JANELA | False: ABRE A JANELA PARA VISUALIZAR O PROCESSO
SCROLL_PAGE = True #SE DESEJAR PEGAR UMA QUANTIDADE MAIOR DE ESTABELECIMENTO DEIXAR COMO True
SCROLL_TOTAL = 1 #QUANTTIDADE DE VEZES QUE SERA FEITO SCROLL NA PAGINA, MAIS MAIOR O NUMEO MAIOR SERA A QUANTIDADE DE DADOS CAPTURADOS


#VARIAVEIS COM O CAMINHOS DA ONDE OS ARQUIVOS DEVEM SER GERADOS
JSON_OUTPUT = r"response.json" #ARQUIVO JSON
EXCEL_OUTPUT = r"response.xlsx" #ARQUIVO EXCEL
LOG_FILE = r"automation.log" #ARQUIVO DE LOG